Integrate sigfm algorithm
rootd/libfprint pull request #12
Opened 2022-11-06 15:04 UTC by 0x00002a

This integrates the sigfm algorithm into libfprint. I've put the commits on my goodix branch as it allowed me to test it properly. @mpi3d I remember you asked in discord if I could put these changes directly onto libfprint main and not the goodix branch, I think this PR is a good place to discuss that and hopefully these commits can be cherry picked over if thats needed.

Results are pretty good, as long as you make sure to move your finger around on the scanner when enrolling so it gets lots of different shots, the acceptance rate is pretty high and I've so far got no false positives. 

## PR outline

### C++/sigfm side

- sigfm is added as another library to be built, and put at the same level as the other algorithms (e.g. nbis) in the tree
- the sigfm library depends on `opencv` (and also `doctest` for the tests, handled by a wrap so its automatic install), and is built with c++. I'm not 100% sure which version of c++ is needed but I would guess at c++17, I've avoided c++20 as I don't want to restrict the compiler versions we can use too much
- the sigfm library offers a C API in `sigfm.hpp` (maybe should rename to `.h`?) which forward declares the `SfmImgInfo` struct and all the functions for dealing with the algorithm
- the `SfmImgInfo` struct stores the extracted keypoints and descriptors, and the C api deals in pointers to it. This lets the api communicate with C and be threaded through the libfprint internal api while still having access to c++ niceties like `std::vector` (and preventing us from having to convert the keypoints and descriptors to some C type)
- serialization and deserialization to binary is also supported (needed by libfprint to store enrolled fingerprints), it uses a homemade `stream` struct and some template magic (which would be less horrible with c++20 concepts)

### C/libfprint side

- There is a new option for the image device class `algorithm`, which lets you pick between sigfm or nbis (defaulting to nbis), this is used to initalise prints which also store their algorithm (`type`)
- `FpImage`'s now store an `SfmImgInfo*` alongside the minutiae, this will be uninitialised until `fp_image_extract_sfm_info` is called (mirroring `minutiae` and `fp_image_detect_minutiae`), this is called automatically by `fpi_image_device_image_captured` if the device uses sigfm (same as for nbis and minutiae)
- verification now checks the type of the print and either calls the bz3 matcher or the sfm one

From the perspective of drivers, all thats needed is to add `<image device class ptr>->algorithm = FPI_DEVICE_ALGO_SIGFM` and libfprint will do the rest.

## Breaking changes that need discussion
-[] `bz3_threshold` is now also used for the threshold for sigfm scores. Ideally it would be renamed to like `score_threshold` or something but this would require refactoring all the existing drivers (which is piss easy with tooling but probably needs to be discussed with upstream)

2022-11-06 16:10 UTC, 0x00002a commented
I've merged the rootd changes (I originally did goodixtls but now I've also done sigfm). Note the example `enroll` and `verify` now timeout when running, theres an issue there with the timeout timer starting at some point where it shouldn't (guessing just before waiting on user input?), anyway it seems to work with fprintd but its an issue we might want to look into

2022-11-06 16:23 UTC, mpi3d commented
@0x00002a First of all, Thanks for your work!

This is what's in my mind right now:
+ Branch `sigfm` should contain only SIGFM related stuff (and nothing about GoodixTLS stuff)
+ Branch `goodixtls` should contain only GoodixTLS related stuff (same: nothing about SIGFM stuff)
+ Branch `master` is just the one from libfprint (I may/should remove it)
+ We may create a `goodixtls-sigfm` that contains both (Like actual [`0x00002a:0x2a/feat/sigfm`](https://github.com/0x00002a/libfprint/tree/0x2a/feat/sigfm))
+ I'm open to any proposition since you definitely have much more experience on Git than me.

2022-11-06 16:26 UTC, 0x00002a commented
> @0x00002a First of all, Thanks for your work!
> 
> This is what's in my mind right now:
> 
>     * Branch `sigfm` should contain only SIGFM related stuff (and nothing about GoodixTLS stuff)
> 
>     * Branch `goodixtls` should contain only GoodixTLS related stuff (same: nothing about SIGFM stuff)
> 
>     * Branch `master` is just the one from libfprint (I may/should remove it)
> 
>     * We may create a `goodixtls-sigfm` that contains both (Like actual [`0x00002a:0x2a/feat/sigfm`](https://github.com/0x00002a/libfprint/tree/0x2a/feat/sigfm))
> 
>     * I'm open to any proposition since you definitely have much more experience on Git than me.

Yeah that is neat, I like it. What I can do then is like I said remove the goodixtls changes from this branch and make a goodixtls-sigfm using those. I can do it destructively (removing the files from each commit in the history) or non-destructively (adding a new commit that reverts the changes). Destructively is potentially cleaner overall but would require a force push to this branch (or a new PR)

2022-11-06 16:29 UTC, mpi3d commented
> > @0x00002a First of all, Thanks for your work!
> > This is what's in my mind right now:
> > ```
> > * Branch `sigfm` should contain only SIGFM related stuff (and nothing about GoodixTLS stuff)
> > 
> > * Branch `goodixtls` should contain only GoodixTLS related stuff (same: nothing about SIGFM stuff)
> > 
> > * Branch `master` is just the one from libfprint (I may/should remove it)
> > 
> > * We may create a `goodixtls-sigfm` that contains both (Like actual [`0x00002a:0x2a/feat/sigfm`](https://github.com/0x00002a/libfprint/tree/0x2a/feat/sigfm))
> > 
> > * I'm open to any proposition since you definitely have much more experience on Git than me.
> > ```
> 
> Yeah that is neat, I like it. What I can do then is like I said remove the goodixtls changes from this branch and make a goodixtls-sigfm using those. If we make this branch the sigfm one I can do it destructively (removing the files from each commit in the history) or non-destructively (adding a new commit that reverts the changes). Destructively is potentially cleaner overall but would require a force push to this branch (or a new PR)

I'm for the destructive method since it's cleaner

2022-11-06 16:44 UTC, 0x00002a commented
@mpi3d OK, this branch should now just have the sigfm stuff on it

2022-11-06 16:48 UTC, mpi3d commented
Ok thanks. Do you want me to merge it right now or you prefer to keep this open?

2022-11-06 16:49 UTC, 0x00002a commented
Since I don't have push access to this repo its probably best to keep it open since it may need further changes I'm not sure

2022-11-06 16:53 UTC, mpi3d commented
Ok. But I may add some changes too (When I have time of course 🙂). So first I'll ask @rootd to give you write access.

2022-11-06 16:57 UTC, mpi3d commented
> * serialization and deserialization to binary is also supported (needed by libfprint to store enrolled fingerprints), it uses a homemade `stream` struct and some template magic (which would be less horrible with c++20 concepts)

Can you explain this a bit more please. I don't understand what binary serialization/deserialization is.

2022-11-06 17:00 UTC, mpi3d commented
> * the sigfm library offers a C API in `sigfm.hpp` (maybe should rename to `.h`?) which forward declares the `SfmImgInfo` struct and all the functions for dealing with the algorithm

I think that libfprint will prefer to have everything written in pure C and only have bindings to C++.

2022-11-06 17:04 UTC, mpi3d commented
> * `bz3_threshold` is now also used for the threshold for sigfm scores. Ideally it would be renamed to like `score_threshold` or something but this would require refactoring all the existing drivers (which is piss easy with tooling but probably needs to be discussed with upstream)

I think we can ignore this in a first time.

2022-11-06 17:06 UTC, mpi3d commented
Just you you to know I didn't read the code yet.

2022-11-06 17:24 UTC, mpi3d commented
Wait. Last commit should be cleaned too.

2022-11-06 17:24 UTC, 0x00002a commented
> > * the sigfm library offers a C API in `sigfm.hpp` (maybe should rename to `.h`?) which forward declares the `SfmImgInfo` struct and all the functions for dealing with the algorithm
> 
> I think that libfprint will prefer to have everything written in pure C and only have bindings to C++. Is it possible to have only pure C?

depends what you mean by "bindings"? libfprint main is still pure C and compiler by the c compiler, sigfm is compiled by the c++ compiler and needs to be c++ to use opencv

2022-11-06 17:26 UTC, mpi3d commented
> > > * the sigfm library offers a C API in `sigfm.hpp` (maybe should rename to `.h`?) which forward declares the `SfmImgInfo` struct and all the functions for dealing with the algorithm
> > 
> > 
> > I think that libfprint will prefer to have everything written in pure C and only have bindings to C++. Is it possible to have only pure C?
> 
> depends what you mean by "bindings"? libfprint main is still pure C and compiler by the c compiler, sigfm is compiled by the c++ compiler and needs to be c++ to use opencv

That should be ok then.

2022-11-06 17:45 UTC, 0x00002a commented
> Wait. Last commit should be cleaned too.

I forgot I based this branch on a branch with the goodix commits, \*should\* be fixed now but standby for more force pushes in case I've missed something

2022-11-06 17:49 UTC, 0x00002a commented
> > * serialization and deserialization to binary is also supported (needed by libfprint to store enrolled fingerprints), it uses a homemade `stream` struct and some template magic (which would be less horrible with c++20 concepts)
> 
> Can you explain this a bit more please. I don't understand what binary serialization/deserialization is.

libfprint stores enrolled fingerprint data as binary files. So we need to serialize the keypoint and descriptors to a binary format that we can later read back (deserialize) to verify fingerprints

2022-11-06 18:51 UTC, mpi3d commented on subprojects/doctest.wrap
> +[wrap-file]
What does this file do?

2022-11-06 19:10 UTC, mpi3d reviewed
I saw that a lot of lines were formatted. Do you mind that we let the format as is? I can do it if you're too lazy 😀. But I think it will help a lot if we try to minimize commits.

2022-11-06 19:15 UTC, mpi3d requested changes
We definitely need to update functions documentation.

2022-11-06 19:26 UTC, mpi3d reviewed
What does `sfm` stand for in fonction names?

2022-11-06 19:59 UTC, 0x00002a commented
> I saw that a lot of lines were formatted. Do you mind that we let the format as is? I can do it if you're too lazy grinning. But I think it will help a lot if we try to minimize commits.

yeah I have a clang-format file I can send to you if you want, I couldn't find any existing one for the project unfortunately but if there is a style guide and I've missed it that would be ideal

2022-11-06 19:59 UTC, 0x00002a commented
> What does `sfm` stand for in fonction names?

sigfm

2022-11-06 20:00 UTC, 0x00002a commented on subprojects/doctest.wrap
> +[wrap-file]
pulls in doctest when configuring the project. Its a meson feature [docs](https://mesonbuild.com/Wrap-dependency-system-manual.html)

2022-11-06 21:08 UTC, mpi3d commented on subprojects/doctest.wrap
> +[wrap-file]
I see.

2022-11-06 21:16 UTC, mpi3d commented
> > What does `sfm` stand for in fonction names?
> 
> sigfm

I think that we should use `sigfm` entirely. `sfm` brings confusion and `sigfm` is just one more letter compared to `nbis`. Two more compared to `bz3` but that's fine. We shouldn't be that lazy 😉.

2022-11-06 21:42 UTC, mpi3d commented
> > I saw that a lot of lines were formatted. Do you mind that we let the format as is? I can do it if you're too lazy grinning. But I think it will help a lot if we try to minimize commits.
> 
> yeah I have a clang-format file I can send to you if you want, I couldn't find any existing one for the project unfortunately but if there is a style guide and I've missed it that would be ideal
> 
> Oh wait did you mean remove the formatted lines from the history?

I don't think they have a styling guide. They just have a script: `scripts/uncrustify.sh` to check basic formatting issues. And yeah, removing formatted lines from the history would be great. 👍

2022-11-06 21:55 UTC, 0x00002a commented
> > > I saw that a lot of lines were formatted. Do you mind that we let the format as is? I can do it if you're too lazy grinning. But I think it will help a lot if we try to minimize commits.
> > 
> > 
> > yeah I have a clang-format file I can send to you if you want, I couldn't find any existing one for the project unfortunately but if there is a style guide and I've missed it that would be ideal
> > Oh wait did you mean remove the formatted lines from the history?
> 
> I don't think they have a styling guide. They just have a script: `scripts/uncrustify.sh` to check basic formatting issues. And yeah, removing formatted lines from the history would be great. +1

Thats just what I was looking for, thanks!

2022-11-06 22:24 UTC, 0x00002a commented
OK I've run uncrustify using their config over the history and it seems to have worked

2022-11-06 23:52 UTC, rootd commented
> Ok. But I may add some changes too (When I have time of course 🙂). So first I'll ask @rootd to give you write access.

Done

2022-11-08 17:21 UTC, mpi3d requested changes
I found some remaining `sfm` strings. I hope I didn't forget one. Can you update that please?

2022-11-08 17:21 UTC, mpi3d commented on libfprint/fp-image.c
> +} ExtractSfmData;
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/fp-image.c
> +fp_image_sigfm_extract_free (ExtractSfmData * data)
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/fp-image.c
> +  ExtractSfmData * data = g_task_get_task_data (task);
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/fp-image.c
> +  ExtractSfmData * data = task_data;
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/fp-image.c
> +  ExtractSfmData * data = g_new0 (ExtractSfmData, 1);
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/sigfm/sigfm.cpp
> +SigfmImgInfo* sigfm_extract(const SfmPix* pix, int width, int height)
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/sigfm/sigfm.hpp
> +typedef unsigned char SfmPix;
Sfm -> Sigfm

2022-11-08 17:21 UTC, mpi3d commented on libfprint/sigfm/sigfm.hpp
> +SigfmImgInfo* sigfm_extract(const SfmPix* pix, int width, int height);
Sfm -> Sigfm

2022-11-08 20:14 UTC, 0x00002a commented
That should've got them all, for both btw I just did `sed -i s/sfm/sigfm`, sed is case sensitive and so was the grep tool I was using (ripgrep), I've done `s/Sfm/Sigfm` now and searched case-insensitively so I think we're good

2022-11-08 21:08 UTC, mpi3d submitted a review, later dismissed

2022-11-08 21:13 UTC, mpi3d commented
Everything seems fine but I still need to check some things here and there.

2022-11-14 13:44 UTC, 0x00002a commented on libfprint/fp-image.c
> +  if (sigfm_keypoints_count (data->sigfm_info) == 0)
Thanks, I'll take a look at how it acts with my sensor

2022-11-14 14:04 UTC, 0x00002a commented on libfprint/fp-image.c
> +  if (sigfm_keypoints_count (data->sigfm_info) == 0)
I'm not getting much difference. The scanner already doesn't accept my fingernail and fingerprints or just random parts of my hand get about the same score (somewhere around 200)

2022-11-14 17:42 UTC, 0x00002a commented on libfprint/fp-image.c
> +  if (sigfm_keypoints_count (data->sigfm_info) == 0)
well my scanner (5110) doesn't even register a finger if its the nail so its really an issue, I suppose we could just hardcode 100 but it feels like a bit of a hack

2022-11-14 21:28 UTC, mpi3d commented on libfprint/fp-image.c
> +  if (sigfm_keypoints_count (data->sigfm_info) == 0)
Ok. Unfortunately, OpenCV will always find a lot of features on any image. Since it's not specific for fingerprints.
Also I think that 100 if to high. Something like 25 - 50 should be fine for every device.

2022-11-19 14:18 UTC, mpi3d commented on libfprint/fpi-image.h
> +#include "sigfm/sigfm.hpp"
@0x00002a Is this necessary?

2022-11-19 14:24 UTC, 0x00002a commented on libfprint/fpi-image.h
> +#include "sigfm/sigfm.hpp"
I'm not sure, probably not here. Remove it and see if it compiles :p

2022-11-19 14:40 UTC, mpi3d commented
@0x00002a Can you review commit 7aedccb6c2b3b38d7193b394e908e4eb6022f36c just to make sure everything is ok.

2022-11-19 14:50 UTC, mpi3d commented on libfprint/fp-image.c
> +  if (sigfm_keypoints_count (data->sigfm_info) == 0)
Is commit ba01aea4e9cff6c676871d797805735f1749cfb1 ok?

2022-11-19 15:01 UTC, 0x00002a commented
> @0x00002a Can you review commit [7aedccb](https://github.com/rootd/libfprint/commit/7aedccb6c2b3b38d7193b394e908e4eb6022f36c) just to make sure everything is ok.

Yeah looks correct

2022-11-19 15:02 UTC, mpi3d commented on libfprint/fpi-image.h
> +#include "sigfm/sigfm.hpp"
It does compile, I'll remove it.

2022-11-19 21:41 UTC, mpi3d commented
We will need to remove formatting of non SIGFM related lines (unmodified lines) in commits. Otherwise libfprint devs will reject them. New and edited lines should use the recommended format. But we shouldn't try to format the entire libfprint code (at least not on this branch).

2022-11-20 07:40 UTC, mpi3d commented on libfprint/fpi-image.h
> +#include "sigfm/sigfm.hpp"
My bad, I didn't see that line `SigfmImgInfo * sigfm_info;` was added.
So even if it does compile, I'll not change anything.

2022-11-20 12:25 UTC, mpi3d commented on libfprint/fp-image.c
> +                               "No keypoints found");
Right, thanks

2022-11-20 13:59 UTC, mpi3d commented
I'll merge. Then I need to edit things before the libfprint merge.

2022-11-20 13:59 UTC, merged